from typing import Dict, Iterator, List

class Device:
    def open(self, manufacturer: int, product: int, serial: str) -> None: ...
    def close(self) -> None: ...
    def send_feature_report(self, report: List[int]) -> None: ...
    def get_feature_report(self, report_num: int, max_length: int) -> List[int]: ...
    def write(self, buff: List[int]) -> int: ...

def enumerate(vendor_id: int, product_id: int) -> Iterator[Dict[str, str]]: ...
def device() -> Device: ...
